import type { Metadata } from "next";
import Search from "../components/SearchBar";
import "../styles/globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark:bg-gray-400">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  );
}
